version: "2.1"
services:
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
     - ./:/bare-bones-api/
    working_dir: /bare-bones-api
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://user:password@db/af_barebones"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: af_barebones
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
